name : sample setup React Ci / workflow

on:
  push:
    branches:
      -master 
      -main

jobs:
  build-and-test:
    runs-on: ubantu-latest
    steps:
      -name: install Node JS
      -uses: actions/setup-node@v6
      with:
          node-version: 24